defaults:
  - _self_
  - env: sql_generation
  - override hydra/launcher: local
  - override hydra/output: local
hydra:
  job:
    chdir: True
model: llama3
temperature: 1.0
suffix: llama3  # suffix for generated files (indicates LLM model)
iteration: 1 # how many iterations of Eureka to run
sample: 3 # number of Eureka samples to generate per iteration
max_iterations: 3000 # RL Policy training iterations (decrease this to make the feedback loop faster)
num_eval: 5 # number of evaluation episodes to run for the final reward